<?php
/**
 * VMCDRomApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * vSphere Automation REST Resources
 *
 * The folders within this collection represent the Rest API resources and the different operations that can be performed on each. These are individual requests. In many cases, each request will require input that would come from other requests. It is left up to the user to insert the correct data into the URL, query parameters and request bodies for the requests to work correctly. Refer to the ReST API Documentation for further help.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * VMCDRomApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VMCDRomApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restVcenterVmVm19HardwareCdrom3000Patch
     *
     * CD-Rom: Update.
     *
     */
    public function testRestVcenterVmVm19HardwareCdrom3000Patch()
    {
    }

    /**
     * Test case for restVcenterVmVm19HardwareCdromGet
     *
     * CD-Rom: List for a single VM.
     *
     */
    public function testRestVcenterVmVm19HardwareCdromGet()
    {
    }

    /**
     * Test case for restVcenterVmVm19HardwareCdromPost
     *
     * CD-Rom: Create SATA.
     *
     */
    public function testRestVcenterVmVm19HardwareCdromPost()
    {
    }

    /**
     * Test case for restVcenterVmVm22HardwareCdrom3001Get
     *
     * CD-Rom: Get details for a single VM.
     *
     */
    public function testRestVcenterVmVm22HardwareCdrom3001Get()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareCdrom16000ConnectPost
     *
     * CD-Rom: Connect.
     *
     */
    public function testRestVcenterVmVm33HardwareCdrom16000ConnectPost()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareCdrom16000DisconnectPost
     *
     * CD-Rom: Disconnect.
     *
     */
    public function testRestVcenterVmVm33HardwareCdrom16000DisconnectPost()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareCdrom3000Delete
     *
     * CD-Rom: Delete.
     *
     */
    public function testRestVcenterVmVm33HardwareCdrom3000Delete()
    {
    }
}
