<?php
/**
 * VMParallelApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * vSphere Automation REST Resources
 *
 * The folders within this collection represent the Rest API resources and the different operations that can be performed on each. These are individual requests. In many cases, each request will require input that would come from other requests. It is left up to the user to insert the correct data into the URL, query parameters and request bodies for the requests to work correctly. Refer to the ReST API Documentation for further help.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * VMParallelApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VMParallelApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallel10000ConnectPost
     *
     * Connect.
     *
     */
    public function testRestVcenterVmVm33HardwareParallel10000ConnectPost()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallel10000DisconnectPost
     *
     * Disconnect.
     *
     */
    public function testRestVcenterVmVm33HardwareParallel10000DisconnectPost()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallel10000Get
     *
     * Details.
     *
     */
    public function testRestVcenterVmVm33HardwareParallel10000Get()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallel10001Delete
     *
     * Delete.
     *
     */
    public function testRestVcenterVmVm33HardwareParallel10001Delete()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallel10001Patch
     *
     * Update.
     *
     */
    public function testRestVcenterVmVm33HardwareParallel10001Patch()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallelGet
     *
     * List.
     *
     */
    public function testRestVcenterVmVm33HardwareParallelGet()
    {
    }

    /**
     * Test case for restVcenterVmVm33HardwareParallelPost
     *
     * Create.
     *
     */
    public function testRestVcenterVmVm33HardwareParallelPost()
    {
    }
}
